/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.practice;

import org.junit.Test;

import com.corejava.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
